"""Add tag_rules table and tags uniqueness constraint

Revision ID: add_tag_rules
Revises: c82f33e6cc89
Create Date: 2026-02-01 21:46:00.000000

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "add_tag_rules"
down_revision = "c82f33e6cc89"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Add uniqueness constraint for tags (user_id, label)
    op.create_unique_constraint("uq_tags_user_id_label", "tags", ["user_id", "label"])

    # Create tag_rules table
    op.create_table(
        "tag_rules",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("tag_id", sa.Uuid(), nullable=False),
        sa.Column(
            "name", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True
        ),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column(
            "payee_contains", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True
        ),
        sa.Column(
            "description_contains",
            sqlmodel.sql.sqltypes.AutoString(length=500),
            nullable=True,
        ),
        sa.Column(
            "payee_regex", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True
        ),
        sa.Column(
            "description_regex",
            sqlmodel.sql.sqltypes.AutoString(length=500),
            nullable=True,
        ),
        sa.Column("amount_min", sa.DECIMAL(precision=32, scale=2), nullable=True),
        sa.Column("amount_max", sa.DECIMAL(precision=32, scale=2), nullable=True),
        sa.Column(
            "currency", sqlmodel.sql.sqltypes.AutoString(length=3), nullable=True
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.tag_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tag_rules_user_id"), "tag_rules", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_tag_rules_tag_id"), "tag_rules", ["tag_id"], unique=False
    )
    op.create_index(
        "ix_tag_rules_user_enabled_priority",
        "tag_rules",
        ["user_id", "enabled", "priority"],
        unique=False,
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tag_rules_user_enabled_priority", table_name="tag_rules")
    op.drop_index(op.f("ix_tag_rules_tag_id"), table_name="tag_rules")
    op.drop_index(op.f("ix_tag_rules_user_id"), table_name="tag_rules")
    op.drop_table("tag_rules")
    op.drop_constraint("uq_tags_user_id_label", "tags", type_="unique")
    # ### end Alembic commands ###
