"""Add CASCADE delete to transaction_tags foreign keys

Revision ID: add_cascade_to_transaction_tags
Revises: add_tag_rules
Create Date: 2026-02-01 22:00:00.000000

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "add_cascade_to_transaction_tags"
down_revision = "add_tag_rules"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop and recreate transaction_tags table with cascade on tag_id FK
    # We need to recreate the table because SQLite doesn't support ALTER CONSTRAINT
    # and we want to be consistent across database backends

    # First, create a backup table with the same data
    op.execute("""
        CREATE TABLE transaction_tags_backup (
            transaction_id UUID NOT NULL,
            tag_id UUID NOT NULL,
            PRIMARY KEY (transaction_id, tag_id),
            FOREIGN KEY (transaction_id) REFERENCES "transaction"(id),
            FOREIGN KEY (tag_id) REFERENCES tags(tag_id) ON DELETE CASCADE
        )
    """)

    # Copy data
    op.execute("""
        INSERT INTO transaction_tags_backup (transaction_id, tag_id)
        SELECT transaction_id, tag_id FROM transaction_tags
    """)

    # Drop old table
    op.drop_table("transaction_tags")

    # Rename backup table
    op.execute("ALTER TABLE transaction_tags_backup RENAME TO transaction_tags")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Remove cascade by recreating the table
    op.execute("""
        CREATE TABLE transaction_tags_backup (
            transaction_id UUID NOT NULL,
            tag_id UUID NOT NULL,
            PRIMARY KEY (transaction_id, tag_id),
            FOREIGN KEY (transaction_id) REFERENCES "transaction"(id),
            FOREIGN KEY (tag_id) REFERENCES tags(tag_id)
        )
    """)

    op.execute("""
        INSERT INTO transaction_tags_backup (transaction_id, tag_id)
        SELECT transaction_id, tag_id FROM transaction_tags
    """)

    op.drop_table("transaction_tags")
    op.execute("ALTER TABLE transaction_tags_backup RENAME TO transaction_tags")

    # ### end Alembic commands ###
